### ISSUE TITLE
Incompatible with Angular's HashLocationStrategy

### ISSUE THREAD

**Issue by don-noonan** [blackbaud/skyux-lib-addin-client#25]
Attempting to create a SKY UX Add-in that uses Angular's [HashLocationStrategy](https://angular.io/api/common/HashLocationStrategy). This is documented as supported by SKY UX through the useHashRouting property of skyuxconfig.json.

**Expected Behavior:**

Setting the useHashRouting property to true in skyuxconfig.json would result in a working Add-in.

**Actual Behavior:**

Add-in no longer works. Enters ngOnInit but does not succeed in subscribing to the Add-in Client Service.

**Reproduction Steps:**

skyux new -t addin
root directory? addin-host-testing
repo URL?
cd skyux-spa-addin-host-testing
skyux generate component my-button/my-button
code .
Add new file my-button/index.html
Add `<my-button></my-button>`
Copy contents of my-button-component.ts from addin-hello-world sample on GitHub.
skyux build
skyux serve -l local
set add-in URL to https://localhost:8000/addin-host-testing/my-button

![image](https://user-images.githubusercontent.com/24811694/65698357-60569700-e04a-11e9-8f66-92b66183a756.png)

View Development Office Home Action area:
 
![image](https://user-images.githubusercontent.com/24811694/65698387-6c425900-e04a-11e9-95ca-e891cd22c2bd.png)
 
Confirmed that it works.
 
Now let's enable hash routing and see what happens…
 
enable useHashRouting via skyuxconfig.json
skyux build
skyux serve -l local
 
Update add-in URL to https://localhost:8000/addin-host-testing/#/my-button

Confirmed that it no longer works.

**Comment by michael-tims** [comment]
@don-noonan This is fixed now, as of this morning, and your button add-in should begin to display.  No client changes are required on your end.
