### ISSUE TITLE
Incompatible with Node 8.11.3 and NPM 6.4.0

### ISSUE THREAD

**Issue by blackbaud-joshlandi** [blackbaud/skyux-lib-addin-client#5]
Tried installing to a SPA with:

@blackbaud/skyux 2.18.0
@blackbaud/skyux-builder 1.15.0

**Expected Behavior**:

    SPA would compile and serve successfully.

**Actual Behavior**:

`tsconfig.json` file in `@blackbaud/skyux-lib-addin-client` can't resolve reference to tsconfig in skyux-builder because NPM handles references differently in later versions.  `node_modules` doesn't exist in the root directory of `skyux-lib-addin-client` when on latest Node and NPM so the path `./node_modules/@blackbaud/skyux-builder/tsconfig` is faulty in this case.

**Comment by Blackbaud-BobbyEarl** [comment]
Can you clarify which version of `npm` you're seeing this behavior on?  `npm` doesn't seem to have a `6.4.0` version.  https://github.com/npm/npm/releases

**Comment by blackbaud-joshlandi** [comment]
Well then i'm confused.  This is what `npm -v` brings up locally.

![image](https://user-images.githubusercontent.com/12849517/44288387-32dfcd00-a23e-11e8-91f4-738c507bd292.png)

**Comment by blackbaud-joshlandi** [comment]
I think it's fresh off the presses.  I'll try the previous version so i'm not using something **too** new.

https://blog.npmjs.org/post/177030805020/release-npm640

**Comment by Blackbaud-BobbyEarl** [comment]
LOL, beat me too it.  Anyway...

Can you elaborate on you problem?  You have a SPA with the versions mentioned above and you're unable to run `skyux serve` or `skyux build`?

**Comment by blackbaud-joshlandi** [comment]
**The error when serving:**

![image](https://user-images.githubusercontent.com/12849517/44340947-7744b600-a454-11e8-8e87-cc4121f216cb.png)


**The tsconfig.json file:**

![image](https://user-images.githubusercontent.com/12849517/44341009-ad823580-a454-11e8-8f58-c45ee15391e6.png)


The path is relative but later versions of npm flatten references right?  So it probably avoided the local reference and is just using the top level reference that our repo's `package.json` installs.

**Comment by Blackbaud-BobbyEarl** [comment]
In the case of what @blackbaud-joshlandi has discovered... users will now need to install `@blackbaud/sky-addin-client` since it's listed as a peer dependency (so they can control the version).  I believe we'll need to update the README/docs to make this explicit @Blackbaud-BenLambert.

I'm going to close this issue.

**Comment by Blackbaud-BenLambert** [comment]
Fixed via this PR:
https://github.com/blackbaud/skyux-lib-addin-client/pull/6
